Adding OTP server protocol in P
BerkeleyLearnVerify/p-secure pull request #1
Opened 2019-09-09 20:33 UTC by ShivKushwah

2019-09-09 20:41 UTC, ankushdesai requested changes
Please fix the comments and create another pull request

2019-09-09 20:41 UTC, ankushdesai commented on OTP-Server-P-Sample/CMakeLists.txt
> +	~/Research/P/Bld/Drops/Prt/include/PrtConfig.h
Rather than include each file, you should add directory. Please refer to the Cmake files in Drona and in P repo.

2019-09-09 20:41 UTC, ankushdesai commented on OTP-Server-P-Sample/PingPong.p
> +fun _CREATEMACHINE(cner: machine, typeOfMachine: int, param : any, newMachine: machine) : machine
This function is not needed, you can directly create the machine using "new"

2019-09-09 20:41 UTC, ankushdesai commented on OTP-Server-P-Sample/PingPong.p
> +			container = _CREATECONTAINER();
Container is not used. We will add things later related to Enclave.

2019-09-09 20:41 UTC, ankushdesai commented on OTP-Server-P-Sample/PrtDistHelp.p
> +// unreliable send
Drop this file completely, its not needed

2019-09-10 08:10 UTC, ShivKushwah commented on OTP-Server-P-Sample/PingPong.p
> +fun _CREATECONTAINER() : machine
For some reason, if I comment out this function, my program crashes. I am unable to find references to this function in the code.

2019-09-11 04:05 UTC, closed without merging