added OTP P Sample
BerkeleyLearnVerify/p-secure pull request #2
Opened 2019-09-11 04:04 UTC by ShivKushwah

2019-09-11 04:05 UTC, ShivKushwah commented on OTP-P-Sample/OTPServer.p
> +fun _CREATECONTAINER() : machine
For some reason, if I comment out this function, my program crashes. I am unable to find references to this function in the code.

2019-09-13 18:18 UTC, ankushdesai commented on OTP-P-Sample/OTPServer.p
> +			raise (Success);
You can delete the success event and replace `raise(Success)` by `goto GenerateOTPCode;`

2019-09-13 18:21 UTC, ankushdesai requested changes

2019-09-13 18:21 UTC, ankushdesai commented on OTP-P-Sample/OTPServer.p
> +          	raise (Success);
here also you can delete the success and done events and replace raise by direct jumps to states using goto.

2019-09-13 18:21 UTC, ankushdesai commented on OTP-P-Sample/OTPServer.p
> +          raise (Success);
delete success event and replace 'raise(successs)' with goto nameofstate;

2019-09-15 19:42 UTC, ankushdesai commented
This is great, as next step please take to Sumukh on how to work with Foreign functions and get started on invoking SGX functions with this.

2019-09-15 19:42 UTC, merged